---
dependencies: []

galaxy_info:
  author: lik
  description: Install and configure CSF/LFD (https://configserver.com/cp/csf.html)
  min_ansible_version: 2.9
  license: MIT
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - wheezy
    - jessie
    - stretch
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
    - bionic
  galaxy_tags:
    - csf
    - lfd
    - firewall
    - iptables
    - networking
    - system
