---
- name: Install SNMP on Debian-based systems
  ansible.builtin.apt:
    name: snmpd
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install SNMP on RedHat-based systems
  ansible.builtin.yum:
    name: net-snmp
    state: present
  when: ansible_os_family == "RedHat"

- name: Configure SNMP using a template
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart SNMP service

- name: Ensure SNMP service is enabled and started
  ansible.builtin.service:
    name: snmpd
    state: started
    enabled: true
