- name: Check if EPEL repo file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repo_stat

- name: Backup existing EPEL repo file
  ansible.builtin.copy:
    src: /etc/yum.repos.d/epel.repo
    dest: /etc/yum.repos.d/epel.repo.bak
    mode: "0644"
    remote_src: true
  when: epel_repo_stat.stat.exists

- name: Set up custom EPEL repo
  ansible.builtin.template:
    src: epel.repo.j2
    dest: /etc/yum.repos.d/epel.repo
    mode: "0644"
