- name: Backup existing EPEL repo file
  ansible.builtin.copy:
    src: /etc/yum.repos.d/epel.repo
    dest: /etc/yum.repos.d/epel.repo.back
    mode: "0644"
    remote_src: true

- name: Disable metalink URLs in EPEL repo
  ansible.builtin.replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: "^(metalink=.*)$"
    replace: '#\1'

- name: Replace EPEL base URLs with custom mirror
  ansible.builtin.replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: '^#baseurl=https://download.example/pub/epel'
    replace: "baseurl=https://ir.epel.sindad.cloud"
