---
- name: Ensure the group exists
  ansible.builtin.group:
    name: "{{ item.group }}"
    state: present
  loop: "{{ users }}"
  when: item.group is defined

- name: Ensure users are created or deleted
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    create_home: "{{ item.create_home }}"
    state: "{{ item.state | default('present') }}"
    password: "{{ item.password }}"
    password_expire_min: "{{ item.password_expire_min | default(0) }}"
    password_expire_max: "{{ item.password_expire_max | default(99999) }}"
    generate_ssh_key: "{{ item.ssh_key | default(false) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(2048) }}"
    ssh_key_file: "{{ item.ssh_key_file | default('.ssh/id_rsa') }}"
  loop: "{{ users }}"