- name: Set up blackbox popsite
  hosts: blackbox
  become: true

  pre_tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: which docker
      register: docker_check
      changed_when: false
      ignore_errors: true

    - name: Set fact if Docker is missing
      ansible.builtin.set_fact:
        docker_not_installed: "{{ docker_check.rc != 0 }}"

  roles:
    - role: common
    - role: docker
      when: docker_not_installed | bool
    - role: blackbox
