- name: Install cPanel/WHM
  hosts: all
  become: true

  roles:
    - role: epel
      tags:
        - epel
    - role: common
      tags:
        - common
        - base_packages
    - role: cpanel
      tags:
        - cpanel
