- name: Disable SELinux
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Stop and disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Create cPanel profile directory
  ansible.builtin.file:
    path: /root/cpanel_profile
    state: directory
    mode: "0755"

- name: Configure cPanel profile
  ansible.builtin.copy:
    dest: "/root/cpanel_profile/cpanel.config"
    content: |
      mysql-version=10.5
    mode: "0644"

- name: Download and install cPanel
  block:
    - name: Install wget
      ansible.builtin.yum:
        name: wget
        state: present

- name: Download latest cPanel installer
  ansible.builtin.get_url:
    url: http://httpupdate.cpanel.net/latest
    dest: /home/latest
    mode: "0755"

- name: Run cPanel installer
  ansible.builtin.command: sh /home/latest
  changed_when: false

- name: Disable network and enable NetworkManager
  block:
    - name: Disable network service
      ansible.builtin.systemd:
        name: network
        enabled: false

- name: Enable and restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: restarted
